### ISSUE TITLE
Document how to contribute

### ISSUE THREAD

**Issue by cornfeedhobo** [askblaker/k3s.rocks#18]
Could you add documentation for your local development cycle?

**Comment by askblaker** [comment]
@cornfeedhobo could you add some more detail or an example of what you are looking for?

**Comment by cornfeedhobo** [comment]
@askblaker I want to be able to build and run the site locally.

**Comment by askblaker** [comment]
Does this help @cornfeedhobo ?
https://github.com/askblaker/k3s.rocks/blob/main/develop.md

**Comment by cornfeedhobo** [comment]
I think so. Let's close this for now and maybe I'll open some PRs for the things I wanted to add, fix, etc.

Thanks for taking care of this!

**Comment by askblaker** [comment]
Ok, great. Thanks for the feedback.
