### ISSUE TITLE
not providing the real ip

### ISSUE THREAD

**Issue by tcurdt** [askblaker/k3s.rocks#25]
It's a great guide - but it seems like the reverse proxy does not provide external remote ip

```
Hostname: whoami-758cdd9df6-nxkgx
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.9
IP: fe80::2445:61ff:fecf:f67c
RemoteAddr: 10.42.0.8:44802
GET /foo HTTP/1.1
Host: whoami.foo.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cache-Control: max-age=0
Sec-Ch-Ua: "Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-Gpc: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 10.42.0.1
X-Forwarded-Host: whoami.foo.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-768bdcdcdd-57nvd
X-Real-Ip: 10.42.0.1
```

**Comment by askblaker** [comment]
Thanks. I think this is a [common issue](https://github.com/k3s-io/k3s/discussions/2997), with different solutions depending on your needs. Are you running as a single node? If so I think the simplest solution can be found in the last paragraph of the [faq](https://k3s.rocks/faq/#x-forwarded-for-and-x-real-ip-proxy-protocol).

**Comment by tcurdt** [comment]
Ah! k3s discussions I didn't search and the FAQ part I did miss.

Yes, this is a single node without external LB.
So I guess [uncommenting this](https://github.com/askblaker/k3s.rocks/blob/16256321c00ae2943752c2d74898a0bcd206c9f3/manifests/traefik-config.yaml#L12) should do the trick.

That said I am not quite sure how this applies in the context of `k3s.rocks` yet.
I don't see which part installs that helm chart yet.

**Comment by askblaker** [comment]
It's not so strange you didn't see it in the FAQ, i only added it now based on this issue. 
The traefik-config file is mentioned [here](https://k3s.rocks/install-setup/#install-k3s).
If you cloned the repo I would try updating main, uncommenting the mentioned lines, and running  
 `kubectl apply -f traefik-config.yaml`
