### ISSUE TITLE
ingress uses deprecated annotation

### ISSUE THREAD

**Issue by tcurdt** [askblaker/k3s.rocks#26]
Great guide - but the ingress seems to use some deprecated ingress annotation

`Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead`

**Comment by askblaker** [comment]
Thanks. Could you please add some more information about when you get this warning?

**Comment by tcurdt** [comment]
I am pretty sure to remember that was during

`cat ./whoami/whoami-ingress-tls.yaml | envsubst | kubectl apply -f -`

**Comment by persunde** [comment]
I also got the same warning when running the command, following the steps on this page: https://k3s.rocks/https-cert-manager-letsencrypt/

``` sh
$ cat ./whoami/whoami-ingress-tls.yaml | envsubst | kubectl apply -f -
Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
ingress.networking.k8s.io/whoami-tls-ingress created
```

**Comment by askblaker** [comment]
@persunde thanks for adding. Would you or @tcurdt be interested in checking out and testing [this branch](https://github.com/askblaker/k3s.rocks/tree/feature/annotation) ?

Or create a pull request if you think anything else is needed ?

**Comment by persunde** [comment]
@askblaker I will test out your branch soon in a couple of days.

Thanks foe the great guide, it has been very helpful.
