### ISSUE TITLE
Update to Traefik v2

### ISSUE THREAD

**Issue by mstruebing** [askblaker/k3s.rocks#29]
As far as I can see, k3s now uses Traefik V2 whereas this guide still uses V1.
This should be updated to reflect the current state.

**Comment by askblaker** [comment]
Hello @mstruebing.

How do you tell that traefik V1 is being used in the guide?

**Comment by mstruebing** [comment]
If I'm not mistaken Traefik v2 uses `IngressRoute` as resources whereas this guide uses `Ingress`, I may be wrong though but this was a change I needed to make in my cluster after upgrading/reinstalling k3s.

**Comment by askblaker** [comment]
Ingressroute is specific to traefik, and Ingress is a standard defined by the Kubernetes project.

This explains it more:
https://community.traefik.io/t/what-is-the-difference-between-ingress-and-ingressroute/10864

I have tried sticking to the standard as much as possible. You can see an example of both in use here:  
https://k3s.rocks/basic-auth/#traefik-ingressroute

I think both will be usable with Traefik v2. And I think using Ingressroute is perfectly fine. My main motivation for staying close to Kubernetes spec that it will be easy to replace components like e.g. Traefik for nginx.

Is there any particular reason you decided to use Ingressroute instead?

**Comment by mstruebing** [comment]
Ah okay I see, so instead of using `IngressRoutes` I could have probably make some changes to the annotations and make it work as well.
Thanks for explaining, I wasn't aware of that.

**Comment by askblaker** [comment]
Yes, for many cases I think you could, but there are probably also many traefik specific features that require or is greatly simplifies things by using Ingressroute.

No problem, happy to help.
