### ISSUE TITLE
Inconsistencies in documentation and manifests

### ISSUE THREAD

**Issue by rkmpa** [askblaker/k3s.rocks#3]
Thanks a lot for this guide. 

I noticed various small potential problems in the guide that I wanted to point out:

1. This [ingress](https://github.com/askblaker/k3s.rocks/blob/a77b612ba706d70b1012e89aea33ab06cca75164/manifests/whoami/whoami-ingress-tls.yaml#L20) will point to the `whoami` service at port 80 while the [service](https://github.com/askblaker/k3s.rocks/blob/a77b612ba706d70b1012e89aea33ab06cca75164/manifests/whoami/whoami-service.yaml#L8) listens on port 5678. Only after fixing this was the `whoami` deployment available for me. 

2. The guide changes directories between sections implicitly. At times, the guide assumes the user is in the manifests directory and at times it is in its parent directory. 

3. During the setup of the registry, the guide instructs to apply a CORS middleware. Since the actual file is not embedded, it is very easy to apply the file without checking its contents. That became quite a time consuming issue to fix, when it came to setting up image deletion for the registry. The middleware does not allow `DELETE` cross-origin requests for some reason. I am not sure if there is a reason the `DELETE` requests are not allowed by default, but if there is none, I would suggest allowing it [here](https://github.com/askblaker/k3s.rocks/blob/a77b612ba706d70b1012e89aea33ab06cca75164/manifests/registry-cors-middleware.yaml#L10)

4. There seems to be no difference between the [ephemeral registry setup](https://github.com/askblaker/k3s.rocks/blob/main/manifests/registry-ephemeral.yaml) and the [localstorage registry setup](https://github.com/askblaker/k3s.rocks/blob/main/manifests/registry-localstorage.yaml). This could lead to users losing data and seems like a mistake as the guide seems to imply the latter would setup a persistent storage.

If desired, I can open a PR for these issues.

**Comment by askblaker** [comment]
Hello! Thank you so much for using it, and for raising this issue.

1. Yes, this should be corrected.

2.  Yes, this should be changed to be consistent. I think the parent folder would be a good choice, but either would work fine.

3. Yes. It was initially like that for no particular reason other than deletion being something that had to be added to. [registry-ui](https://joxit.dev/docker-registry-ui/) . The middleware could probably be changed by itself without issue, but maybe the registry-ui should be be configured to [support deletion](https://joxit.dev/docker-registry-ui/#using-delete) as well.

4. Yes, this is a mistake, and the localstorage one should be changed to actually use localstorage.

A PR for any or all of these points would be appreciated.

Thanks!
